/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mvtech_devices_Scaler */

#ifndef _Included_com_mvtech_devices_Scaler
#define _Included_com_mvtech_devices_Scaler
#ifdef __cplusplus
extern "C" {
#endif

#define	IOC_VDEC_GET_VIDEO_LOSS			0x09
#define IOC_VDEC_ENABLE_MOTION			0x41
#define IOC_VDEC_SET_MOTION_SENS		0x46
#define IOC_VDEC_GET_MOTION_CH 			0x90
#define IOC_VDEC_SET_MOTION_SENS2		0x91
#define IOC_VDEC_SET_MOTION_IRQ			0x92
#define IOC_VDEC_SET_MOTION_CLEAR		0x93

#define MDIN325_IOC_MAGIC            'm'
#define MDIN_OSD_ONOFF			_IOW(MDIN325_IOC_MAGIC, 0x24, char)

#define PIN_IRQ							230
#define CFG_GPIO_DIR 					"/sys/class/gpio"
#define CFG_GPIO_SYS_FILE_EXPORTED_TIME_IN_100MS 	10


/*
 * Class:     com_mvtech_devices_Scaler
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_mvtech_devices_Scaler_open
  (JNIEnv *, jclass);

/*
 * Class:     com_mvtech_devices_Scaler
 * Method:    SetOSD
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_mvtech_devices_Scaler_SetOSD
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_mvtech_devices_Scaler
 * Method:    SetDetect
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_mvtech_devices_Scaler_SetDetection
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_mvtech_devices_Scaler
 * Method:    SetSensitivity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mvtech_devices_Scaler_SetTSensitivity
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mvtech_devices_Scaler
 * Method:    SetSensitivity2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mvtech_devices_Scaler_SetPSensitivity
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mvtech_devices_Scaler
 * Method:    GetMotion
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_mvtech_devices_Scaler_GetMotionSens
  (JNIEnv *, jclass);

/*
 * Class:     com_mvtech_devices_Scaler
 * Method:    GetVideo
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_mvtech_devices_Scaler_GetVideoInputs
  (JNIEnv *, jclass);

/*
 * Class:     com_mvtech_devices_Scaler
 * Method:    SetIrq
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mvtech_devices_Scaler_SetEventEnable
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mvtech_devices_Scaler
 * Method:    SetMotionClear
 * Signature: (I)V
 */
JNIEXPORT jbyte JNICALL Java_com_mvtech_devices_Scaler_SetEventClear
  (JNIEnv *, jclass);

/*
 * Class:     com_mvtech_devices_Scaler
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT void JNICALL Java_com_mvtech_devices_Scaler_close
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
